# Generated by Django 3.1.2 on 2020-11-06 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedfood',
            name='brand_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
