# Generated by Django 3.1.2 on 2020-11-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20201105_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodgroup',
            old_name='serving_weight',
            new_name='serving_weight_g',
        ),
        migrations.RenameField(
            model_name='savedfood',
            old_name='serving_weight',
            new_name='serving_weight_g',
        ),
        migrations.RemoveField(
            model_name='foodgroup',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='foodgroup',
            name='sugars',
        ),
        migrations.RemoveField(
            model_name='savedfood',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='savedfood',
            name='sugars',
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='added_sugar',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='alanine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='alcohol',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='arginine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='ash',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='aspartic_acid',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='betaine',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='caffeine',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='calcium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='carotene_a',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='carotene_b',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='choline',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='copper',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='cystine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='dextrose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='fluoride',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='folate',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='folic_acid',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='fructose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='galactose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='glycine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='histidine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='hydroxyproline',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='iron',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='isoleucine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='lactose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='leucine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='lycopine',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='lysine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='magnesium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='maltose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='manganese',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='menaquinone_4',
            field=models.FloatField(blank=True, help_text='Units: Âµg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='monounsaturated_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='niacin',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_3_ala',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_3_dha',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_3_dpa',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_3_epa',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_3_ete',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_6_aa',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_6_dgla',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_6_ea',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_6_gla',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='omega_6_la',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='pantothenic_acid',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='phenylalanine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='phosphorus',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='phytosterol',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='polyunsaturated_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='proline',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='retinol',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='riboflavin',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='selenium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='serine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='starch',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='sucrose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='theobromine',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='thiamin',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='threonine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='total_protein',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='total_sugar',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='tryptophan',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_b12',
            field=models.FloatField(blank=True, help_text='Units: Âµg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_b6',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_c',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_d',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_d2',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_d3',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_e',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='vitamin_k',
            field=models.FloatField(blank=True, help_text='Units: Âµg', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='water',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='foodgroup',
            name='zinc',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='added_sugar',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='alanine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='alcohol',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='arginine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='ash',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='aspartic_acid',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='betaine',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='caffeine',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='calcium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='carotene_a',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='carotene_b',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='choline',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='copper',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='cystine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='dextrose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='fluoride',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='folate',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='folic_acid',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='fructose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='galactose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='glycine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='histidine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='hydroxyproline',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='iron',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='isoleucine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='lactose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='leucine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='lycopine',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='lysine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='magnesium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='maltose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='manganese',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='menaquinone_4',
            field=models.FloatField(blank=True, help_text='Units: Âµg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='monounsaturated_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='niacin',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_3_ala',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_3_dha',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_3_dpa',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_3_epa',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_3_ete',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_6_aa',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_6_dgla',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_6_ea',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_6_gla',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='omega_6_la',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='pantothenic_acid',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='phenylalanine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='phosphorus',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='phytosterol',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='polyunsaturated_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='proline',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='retinol',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='riboflavin',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='selenium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='serine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='starch',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='sucrose',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='theobromine',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='thiamin',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='threonine',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='total_protein',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='total_sugar',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='tryptophan',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_b12',
            field=models.FloatField(blank=True, help_text='Units: Âµg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_b6',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_c',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_d',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_d2',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_d3',
            field=models.FloatField(blank=True, help_text='Units: µg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_e',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='vitamin_k',
            field=models.FloatField(blank=True, help_text='Units: Âµg', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='water',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AddField(
            model_name='savedfood',
            name='zinc',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='calories',
            field=models.FloatField(blank=True, help_text='Units: kcal', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='cholesterol',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='fiber',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='potassium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='saturated_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='sodium',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='total_carbs',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='foodgroup',
            name='total_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='calories',
            field=models.FloatField(blank=True, help_text='Units: kcal', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='cholesterol',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='fiber',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='potassium',
            field=models.FloatField(blank=True, help_text='Units: mg', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='saturated_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='serving_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='sodium',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='total_carbs',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
        migrations.AlterField(
            model_name='savedfood',
            name='total_fat',
            field=models.FloatField(blank=True, help_text='Units: g', null=True),
        ),
    ]
