# Generated by Django 3.1.2 on 2020-11-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20201107_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfood',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
